# Site configurations
baseurl:
exclude:
    - LICENSE
    - README
    - Makefile
    - _hg

# Repositoriy informations
name: Srain
github: SrainApp/srain
logo: https://raw.githubusercontent.com/SrainApp/srain/master/data/icons/scalable/srain.png
documentation: https://doc.srain.im
screenshots:
    - https://raw.githubusercontent.com/SrainApp/srain/master/doc/_static/srain-joined-channel.png
    - https://raw.githubusercontent.com/SrainApp/srain/master/doc/_static/srain-searched-chennel.png
