# Site configurations
baseurl:
exclude:
    - LICENSE
    - README
    - Makefile
    - _hg

# Project repositoriy informations
name: Srain
github: SrainApp/srain
logo: /assets/images/logo.png
download: http://doc.srain.im/en/latest/install.html
documentation: https://doc.srain.im
screenshots:
    - https://raw.githubusercontent.com/SrainApp/srain/master/doc/_static/srain-joined-channel.png
    - https://raw.githubusercontent.com/SrainApp/srain/master/doc/_static/srain-searched-chennel.png
